name: "run all my test"

on:
  push:
    branches:
      - main
      - lecture/*

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - run: npm test
